# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'NRPortalSonar'
    organization: 'p2nullreturners'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'NRTMPortal'
    cliProjectName: 'NRTMPortal'
    cliSources: './Frontend/'

- task: AzureAppServiceManage@0
  displayName: 'Stop App Service'
  inputs:
    azureSubscription: 'Azure subscription 1(0cfa6593-af85-4dcb-b1a3-7ead93b8def2)'
    Action: 'Stop Azure App Service'
    WebAppName: 'nrtmportal'

- task: NodeTool@0
  displayName: 'Setup Node Environment'
  inputs:
    versionSpec: '10.x'

- task: Npm@1
  displayName: 'NPM Install'
  inputs:
    command: 'install'
    workingDir: './Frontend/'

- task: Npm@1
  displayName: 'NPM Install Angular CLI'
  inputs:
    command: 'custom'
    workingDir: './Frontend/'
    customCommand: 'install -g @angular/cli@latest'

- task: Npm@1
  displayName: 'NPM Build Angular'
  inputs:
    command: 'custom'
    workingDir: './Frontend/'
    customCommand: 'run ng build --prod'

- task: Npm@1
  displayName: 'NPM Test'
  inputs:
    command: 'custom'
    customCommand: 'run test-headless'
    workingDir: './Frontend/'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './Frontend/'
    customCommand: 'run sonar'

#- task: Npm@1
#  displayName: 'NPM Test'
#  inputs:
#    command: 'custom'
#    customCommand: 'run e2e'
#    workingDir: './Frontend/'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Cobertura Code Coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '../coverage/cobertura-coverage.xml'

- task: SonarCloudAnalyze@1
  displayName: 'SonarCloud Analyze'

- task: SonarCloudPublish@1
  displayName: 'Publishing SonarCloud'
  inputs:
    pollingTimeoutSec: '300'

- task: ArchiveFiles@2
  displayName: 'Archive Angular Build Files'
  inputs:
    rootFolderOrFile: 'Frontend/dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Angular App'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(0cfa6593-af85-4dcb-b1a3-7ead93b8def2)'
    appType: 'webApp'
    WebAppName: 'nrtmportal'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- task: AzureAppServiceManage@0
  displayName: 'Start App Service'
  inputs:
    azureSubscription: 'Azure subscription 1(0cfa6593-af85-4dcb-b1a3-7ead93b8def2)'
    Action: 'Start Azure App Service'
    WebAppName: 'nrtmportal'